package com.enic.JsonTrans;

import java.util.Date;

public class TUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tuniu_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Integer tuniuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.owner_name
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.oa_name_en
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String oaNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.nick_name
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_type
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.head_image
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String headImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.space_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Integer spaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.v_user_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Long vUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.open_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.owner_identity_pic_front
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String ownerIdentityPicFront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.owner_identity_pic_reverse
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String ownerIdentityPicReverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.owner_qualification_pic
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String ownerQualificationPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.owner_phone
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String ownerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.owner_identity_no
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String ownerIdentityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.update_time
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.p_value
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private String pValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.channel
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Byte channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.uid
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.earn_secondary_commission
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Byte earnSecondaryCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.customer_service_assigned
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    private Byte customerServiceAssigned;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tuniu_id
     *
     * @return the value of t_user_info.tuniu_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Integer getTuniuId() {
        return tuniuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tuniu_id
     *
     * @param tuniuId the value for t_user_info.tuniu_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setTuniuId(Integer tuniuId) {
        this.tuniuId = tuniuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.owner_name
     *
     * @return the value of t_user_info.owner_name
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.owner_name
     *
     * @param ownerName the value for t_user_info.owner_name
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.oa_name_en
     *
     * @return the value of t_user_info.oa_name_en
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getOaNameEn() {
        return oaNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.oa_name_en
     *
     * @param oaNameEn the value for t_user_info.oa_name_en
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setOaNameEn(String oaNameEn) {
        this.oaNameEn = oaNameEn == null ? null : oaNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.nick_name
     *
     * @return the value of t_user_info.nick_name
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.nick_name
     *
     * @param nickName the value for t_user_info.nick_name
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_type
     *
     * @return the value of t_user_info.user_type
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_type
     *
     * @param userType the value for t_user_info.user_type
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.head_image
     *
     * @return the value of t_user_info.head_image
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.head_image
     *
     * @param headImage the value for t_user_info.head_image
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage == null ? null : headImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.space_id
     *
     * @return the value of t_user_info.space_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Integer getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.space_id
     *
     * @param spaceId the value for t_user_info.space_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.v_user_id
     *
     * @return the value of t_user_info.v_user_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Long getvUserId() {
        return vUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.v_user_id
     *
     * @param vUserId the value for t_user_info.v_user_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setvUserId(Long vUserId) {
        this.vUserId = vUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.open_id
     *
     * @return the value of t_user_info.open_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.open_id
     *
     * @param openId the value for t_user_info.open_id
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.owner_identity_pic_front
     *
     * @return the value of t_user_info.owner_identity_pic_front
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getOwnerIdentityPicFront() {
        return ownerIdentityPicFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.owner_identity_pic_front
     *
     * @param ownerIdentityPicFront the value for t_user_info.owner_identity_pic_front
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setOwnerIdentityPicFront(String ownerIdentityPicFront) {
        this.ownerIdentityPicFront = ownerIdentityPicFront == null ? null : ownerIdentityPicFront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.owner_identity_pic_reverse
     *
     * @return the value of t_user_info.owner_identity_pic_reverse
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getOwnerIdentityPicReverse() {
        return ownerIdentityPicReverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.owner_identity_pic_reverse
     *
     * @param ownerIdentityPicReverse the value for t_user_info.owner_identity_pic_reverse
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setOwnerIdentityPicReverse(String ownerIdentityPicReverse) {
        this.ownerIdentityPicReverse = ownerIdentityPicReverse == null ? null : ownerIdentityPicReverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.owner_qualification_pic
     *
     * @return the value of t_user_info.owner_qualification_pic
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getOwnerQualificationPic() {
        return ownerQualificationPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.owner_qualification_pic
     *
     * @param ownerQualificationPic the value for t_user_info.owner_qualification_pic
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setOwnerQualificationPic(String ownerQualificationPic) {
        this.ownerQualificationPic = ownerQualificationPic == null ? null : ownerQualificationPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.owner_phone
     *
     * @return the value of t_user_info.owner_phone
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getOwnerPhone() {
        return ownerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.owner_phone
     *
     * @param ownerPhone the value for t_user_info.owner_phone
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setOwnerPhone(String ownerPhone) {
        this.ownerPhone = ownerPhone == null ? null : ownerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.owner_identity_no
     *
     * @return the value of t_user_info.owner_identity_no
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getOwnerIdentityNo() {
        return ownerIdentityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.owner_identity_no
     *
     * @param ownerIdentityNo the value for t_user_info.owner_identity_no
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setOwnerIdentityNo(String ownerIdentityNo) {
        this.ownerIdentityNo = ownerIdentityNo == null ? null : ownerIdentityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.update_time
     *
     * @return the value of t_user_info.update_time
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.update_time
     *
     * @param updateTime the value for t_user_info.update_time
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.p_value
     *
     * @return the value of t_user_info.p_value
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public String getpValue() {
        return pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.p_value
     *
     * @param pValue the value for t_user_info.p_value
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setpValue(String pValue) {
        this.pValue = pValue == null ? null : pValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.channel
     *
     * @return the value of t_user_info.channel
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Byte getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.channel
     *
     * @param channel the value for t_user_info.channel
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setChannel(Byte channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.uid
     *
     * @return the value of t_user_info.uid
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.uid
     *
     * @param uid the value for t_user_info.uid
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.earn_secondary_commission
     *
     * @return the value of t_user_info.earn_secondary_commission
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Byte getEarnSecondaryCommission() {
        return earnSecondaryCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.earn_secondary_commission
     *
     * @param earnSecondaryCommission the value for t_user_info.earn_secondary_commission
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setEarnSecondaryCommission(Byte earnSecondaryCommission) {
        this.earnSecondaryCommission = earnSecondaryCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.customer_service_assigned
     *
     * @return the value of t_user_info.customer_service_assigned
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public Byte getCustomerServiceAssigned() {
        return customerServiceAssigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.customer_service_assigned
     *
     * @param customerServiceAssigned the value for t_user_info.customer_service_assigned
     *
     * @mbg.generated Mon Sep 23 18:59:10 CST 2019
     */
    public void setCustomerServiceAssigned(Byte customerServiceAssigned) {
        this.customerServiceAssigned = customerServiceAssigned;
    }

    @Override
    public String toString() {
        return "TUserInfo{" +
                "id=" + id +
                ", tuniuId=" + tuniuId +
                ", ownerName='" + ownerName + '\'' +
                ", oaNameEn='" + oaNameEn + '\'' +
                ", nickName='" + nickName + '\'' +
                ", userType=" + userType +
                ", headImage='" + headImage + '\'' +
                ", spaceId=" + spaceId +
                ", vUserId=" + vUserId +
                ", openId='" + openId + '\'' +
                ", ownerIdentityPicFront='" + ownerIdentityPicFront + '\'' +
                ", ownerIdentityPicReverse='" + ownerIdentityPicReverse + '\'' +
                ", ownerQualificationPic='" + ownerQualificationPic + '\'' +
                ", ownerPhone='" + ownerPhone + '\'' +
                ", ownerIdentityNo='" + ownerIdentityNo + '\'' +
                ", updateTime=" + updateTime +
                ", pValue='" + pValue + '\'' +
                ", channel=" + channel +
                ", uid=" + uid +
                ", earnSecondaryCommission=" + earnSecondaryCommission +
                ", customerServiceAssigned=" + customerServiceAssigned +
                '}';
    }
}